{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "mkdocsWatcher.fullname" . }}-cronjob
  labels:
    {{- include "mkdocsWatcher.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: node-details
            image: "{{ .Values.cronjob.repository }}:{{ .Values.cronjob.tag }}"
            command:
            - /bin/sh
            - -c
            - |
              NODE_DETAILS=$(kubectl get nodes -o json | jq -r '.items[] | {name: .metadata.name, status: .status.conditions[] | select(.type == "Ready") .status, age: .metadata.creationTimestamp, version: .status.nodeInfo.kubeletVersion} | ([.[]]) | @tsv' | awk 'BEGIN{print "|Name|Status|Age|Version|\n     |---|---|---|---|"} {print "     |" $1 "|" $2 "|" $3 "|" $4 "|"}')
              echo "apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: mkdirs-node-details\ndata:\n  node-details.md: |\n     # Node Details\n\n     $NODE_DETAILS\n     Fetched: $(date)" 
              echo "apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: mkdirs-node-details\ndata:\n  node-details.md: |\n     # Node Details\n\n     $NODE_DETAILS\n     Fetched: $(date)" | kubectl apply -f -
              kubectl delete pods -l app=mkdocapp
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
{{- end }}